### ISSUE TITLE
UCESB cannot populate items in client_struct_info with client.setup

### ISSUE THREAD

**Issue by YanzhaoW** [R3BRootGroup/R3BRoot#1021]
**Describe the bug**
In the current version of ucesb (located at 'fake_cvmfs/10/cvmfs_fairroot_v18.8.0_fs_nov22p1_extra/ucesb'):
```text
commit 7d684cda65d5f6ebb89db6848b19d24a6a47244c (origin/master, origin/HEAD, master)
Author: *****
Date:   Fri Nov 24 19:57:39 2023 +0100
```
The struct_info data from ucesb client can't populate its items after calling 
```cpp
ucesb_client_.setup(
                nullptr, 0, ucesb_client_struct_info_, &is_struct_map_success, event_struct_size_)
```
even it returns 0.

However it works with an older version: 
```text
commit a731f2582d6c322f2639a7c723d8e57ea205befb (HEAD -> master, origin/master, origin/HEAD)
Author: *****
Date:   Sun Feb 5 23:41:44 2023 +0100
```

**To Reproduce**
1. In R3BUcesbSource.cxx::156, change the code to
```cpp
    Bool_t status = fClient.setup(NULL, 0, &fStructInfo, &struct_map_success, fEventSize);
    if (status != 0)
    { 
        .... 
    }
     for (auto* item = fStructInfo->_items; item != nullptr; item = item->_next_off_item)
    {
       std::cout << item->_var_name << "\n";
    }
```
2. Run any detector unpacking.
3. With the old version, all variable items can be printed out. With the new version, items are empty.

**System information:**
 - lxir136

**Additional context**
Sorry that I can't find anyone responsible for UCESB in [volunteer list](https://wiki.r3b-nustar.de/daq/volunteers). Neither can I post this issue directly in UCESB Gitlab due to permission restrictions.

@inkdot7 @hanstt

**Comment by inkdot7** [comment]
If it is an ucesb bug (separable / minimizable from r3broot and upexps), please try to join the group gitlab.com/chalmers-subexp and we see what can be done there.

Lack of volunteers should be referred to tech board, management board and collaboration board.  They seem to not be clear on the jurisdiction, so I suggest to contact all at the same time, to avoid being bounced around.

**Comment by YanzhaoW** [comment]
Ok, great. I recreated this issue over there. I guess we could close it here.
