### ISSUE TITLE
Could NOT find GTest

### ISSUE THREAD

**Issue by ManuelXarepe** [R3BRootGroup/R3BRoot#1080]
**Describe the bug**

When trying to cmake a newer version of R3BRoot, we run into the CMAKE error in the picture below. I tested this with an old version of R3BRoot from February, and it works fine.

**To Reproduce**
1. source /u/land/fake_cvmfs/sourceme.sh
2. In the build directory run cmake PATH/TO/R3BRoot

**Expected behavior**
Finish cmake

**Logs / Screenshots**

![error](https://github.com/user-attachments/assets/d73e2824-43ef-4a13-9c25-d4315b2f0717)

**System information (please complete the following information):**
- In this case I was connect as land to lxir136

**Comment by jose-luis-rs** [comment]
Hello @ManuelXarepe 

You can comment this line
#find_package(GTest REQUIRED)
in R3BRoot/CMakeLists.txt

@YanzhaoW, please, could you change the use of GTest only for tests in GitHub?
Thanks

**Comment by YanzhaoW** [comment]
Hi, @ManuelXarepe 

Sorry that I just saw your post. I will fix this today.

@jose-luis-rs 

I think we could just do 
```cmake
find_package(GTest)
```
Without `REQUIRED`, CMake will not load GTest if it doesn't exist.

**Comment by jose-luis-rs** [comment]
Thanks @YanzhaoW

**Comment by YanzhaoW** [comment]
Hi, @ManuelXarepe 

Could you test out the latest version and see whether it fixes the issue?
