### ISSUE TITLE
commit 9b2b2ae won't compile

### ISSUE THREAD

**Issue by miharenthas** [R3BRootGroup/R3BRoot#165]
Hello,
The last commit in the dev branch won't compile with gcc 5.4.0 or gcc 7.2.1
I suspect a compiler flag is missing, since the error is "language construct not recognised", on construct that are standart in C++11.

It happens on line 23 and 24 of R3BPhaseSpaceGenerator.h and line 35:
23: Bool_t Init() override;
24: Bool_t ReadEvent(FairPrimaryGenerator* primGen) override;
//...
35: ClassDefOverride(R3BPhaseSpaceGenerator, 1);

The immediately previous commit does work, and that's the one I'm using.

Cheers,
L.

**Comment by janmayer** [comment]
Hi,
interesting, do you have compiled FairSoft with Root5 or Root6?

Could you post the full compilation output?

**Comment by miharenthas** [comment]
Hi,

I'm using root 5, but it doesn't look like a root error, so much as a compiler complaint.

I'll post the full line later this evening, but it doesn't really tell much more.

Cheers,
L.

**Comment by janmayer** [comment]
It is quite likely a Root5 problem, as the dictionary generator is known for having troubles with some newer C++ keywords. Note that some code doesn't even get built with Root5.

@kresan Should I move the Root5 warning from `neuland/CMakeLists.txt` to the main CMake file?

**Comment by miharenthas** [comment]
Aaaah, yes, now I get it: it might have come from a dictionary (I compile in parallel so some errors may be signalled not exactly net what created them).

I'll try to move to root 6, but that will likely take time, so it's not going to happen before a couple of weeks...

**Comment by kresan** [comment]
@janmayer yes, please move the check for ROOT 5 to the main CMakeLists.txt. But make it a fatal error. ROOT 5 support is stopped. Next release of FairSoft will not have this option. We have decided, to have R3BRoot apr17 the last stable version working with ROOT 5.

**Comment by kresan** [comment]
With #166 ROOT 6 is now a requirement
