### ISSUE TITLE
run_{,aladin}_digi_test.sh.in not found

### ISSUE THREAD

**Issue by miharenthas** [R3BRootGroup/R3BRoot#168]
Hi,

Just merged the dev branch into my local fork and it doesn't cmake itself any more:

CMake Error: File /usr/local/FAIR/R3BRoot/macros/r3b/run_digi_test.sh.in does not exist.
CMake Error at macros/r3b/CMakeLists.txt:36 (configure_file):
  configure_file Problem configuring file

and:

CMake Error: File /usr/local/FAIR/PhD_local/R3BRoot/macros/r3b/run_aladin_digi_test.sh.in does not exist.
CMake Error at macros/r3b/CMakeLists.txt:44 (configure_file):
  configure_file Problem configuring file

By commenting out lines 36-39 and 44-47 the configuration will succeed (it still won't compile, but that's a separate issue which will follow in a few minutes).

Another solution would be to actually add the files to the repository so they are present...

**Comment by kresan** [comment]
Hi,

the files are actually in the repository (in dev branch). Does the problem persist? Did you merge go properly?

Cheers,
Dima

**Comment by kresan** [comment]
** your merge **

**Comment by miharenthas** [comment]
Yes, it did. And yes, they were in the repo (commit 553ff3f24b5847f1af6fe55056ebb94c93409725)
Weird. Probably some older merge had conflicts and I resolved them in a bad way/some other screw up.

I cherry-picked it on the branch I'm using and all went well. Thanks.
