### ISSUE TITLE
testR3BPhaseSpaceGenerator.cxx appears to be broken.

### ISSUE THREAD

**Issue by miharenthas** [R3BRootGroup/R3BRoot#169]
Hi (again),

There's an explicit virtual method override that won't override --and because the keyword override is used, that generates a compiler issue. Indeed, it's a function overload, not a reimplementation.

/usr/local/FAIR/R3BRoot/r3bgen/testR3BPhaseSpaceGenerator.cxx:17:14: error: ‘void {anonymous}::MockFairPrimaryGenerator::AddTrack(Int_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t, Int_t, Bool_t, Double_t, Double_t, Double_t)’ marked ‘override’, but does not override
         void AddTrack(Int_t pdgid,
              ^~~~~~~~

The function takes a different list of parameters from how the virtual method is declared, thus making it an overload instead.

FairPrimaryGenerator.h:83
virtual void FairPrimaryGenerator::AddTrack(Int_t pdgid, Double_t px, Double_t py, Double_t pz,
                        Double_t vx, Double_t vy, Double_t vz,
                        Int_t parent = -1, Bool_t wanttracking = true,
                        Double_t e = -9e9, Double_t tof = 0.,
                        Double_t weight = 0., TMCProcess proc = kPPrimary);

whereas:

testR3BPhaseSpaceGenerator.cxx:17
void testR3BPhaseSpaceGenerator::AddTrack(Int_t pdgid,
                      Double_t px,
                      Double_t py,
                      Double_t pz,
                      Double_t vx,
                      Double_t vy,
                      Double_t vz,
                      Int_t parent = -1,
                      Bool_t wanttracking = true,
                      Double_t e = -9e9,
                      Double_t tof = 0.,
                      Double_t weight = 0.) override

The problem is, the last TMCProcess is missing. Adding it will solve the problem.

I'm using the very last commit in FairRoot/dev.

Some historical background: d.kresan@gsi.de apparently added the new argument to FairPrimaryGenerator::AddTrack with commit 45de553b9da50e89a386f5fd3b40c8289ebf1de2 on the 28th of June this year. Who compile-tested the last commits of R3BRoot appears to have an old FairRoot version (and should update).

---

EDIT: a chat with Vadim clarified why it actually passed the compile-test: I'm using a FairRoot version that is too up to date. Anyhow, this is the solution to a future problem.

**Comment by janmayer** [comment]
Hi, sorry for this.

I'll update my FairRoot and get a PR out for this soon (TM) - which probably also includes updating FairRoot in the continuous integration process.

Note that Github uses `markdown`, you can use it to make stuff easier to read, e.g.
```C++
/usr/local/FAIR/R3BRoot/r3bgen/testR3BPhaseSpaceGenerator.cxx:17:14: error: ‘void {anonymous}::MockFairPrimaryGenerator::AddTrack(Int_t, Double_t, Double_t, Double_t, Double_t, Double_t, Double_t, Int_t, Bool_t, Double_t, Double_t, Double_t)’ marked ‘override’, but does not override
void AddTrack(Int_t pdgid,
^~~~~~~~
```

**Comment by vadimr3b** [comment]
Hi,

commit #174 solved this problem.
