### ISSUE TITLE
Missing file r3bdata/fibData/R3BFi4CalItem.cxx ?

### ISSUE THREAD

**Issue by miharenthas** [R3BRootGroup/R3BRoot#190]
Hi,
After a linker fail with ```R3BFi4CalItem::R3BFi4CalItem(unsigned char, unsigned int, unsigned int, unsigned int, float, float, float, float)```, I noticed that there's an orphan header file:
```/r3bdata/fibData/R3BFi4CalItem.h```
It was added in commit d83d35796ddf4b60e64d018a0921ceac83b36101:
```
$ git rev-list -n 1 HEAD -- $( find . -name '3BFi4CalItem.*' ) #the find command will only find the header
```
doing the same thing for the .cxx doesn't get any result --the file has never been in the repo or was removed before the history began.

Could you please add the file back/remove the header if it's not needed?

Note that the missing .cxx file doesn't affect the build, nor the creation of shared libraries, but only linking against the library in question, libR3BFi4.so.

I can avoid linking against it ATM, but if someone needs the affected class R3BRoot is going to explode in their face...

**Comment by kresan** [comment]
fixed in #198
