### ISSUE TITLE
Missing detectors in R3BMCTrack

### ISSUE THREAD

**Issue by janmayer** [R3BRootGroup/R3BRoot#214]
To reproduce: run test file `macros/r3b/run_sim.C()` directly
Tested with 3b073bf1ee7cc8505ae6c35fa4f3aeaa4aa5a702 (before the macros where removed from the main repository)

The detectors added in
https://github.com/R3BRootGroup/R3BRoot/commit/90c91987d2b833f347f4f77d9e0a43269ac919ed#diff-7fe5d291e474bea07c4c9def6abcc1f7

are missing in `R3BMCTrack::SetNPoints` and `R3BMCTrack::GetNPoints`, which leads to many warning messages during simulation:
```
-E- R3BMCTrack::SetNPoints: Unknown detector ID 17
-E- R3BMCTrack::SetNPoints: Unknown detector ID 18
-E- R3BMCTrack::SetNPoints: Unknown detector ID 22
-E- R3BMCTrack::SetNPoints: Unknown detector ID 23
-E- R3BMCTrack::SetNPoints: Unknown detector ID 24
-E- R3BMCTrack::SetNPoints: Unknown detector ID 25
```

I would highly recommend ditching the current implementation of `fNPoints`, a overcomplicated Bitvector, in favor of, e.g., a std::array with size of the enum `DetectorId`.

Also, I don't know what this is part in `R3BMCStack` does, but is seems somewhat wasteful. Maybe just store the whole `fPointsMap` in `R3BMCTrack`?
```C++
      for (Int_t iDet=kREF; iDet<kLAST; iDet++) {
        pair<Int_t, Int_t> a(iPart, iDet);
        track->SetNPoints(iDet, fPointsMap[a]);
      }
```

**Comment by kresan** [comment]
resolved in #217
