### ISSUE TITLE
Foo& operator=(const Foo&) { return *this; } considered harmful

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#355]
git blame is not very forthcoming, but whoever has written this gem:

  R3BCalifaCrystalCalData& operator=(const R3BCalifaCrystalCalData&) { return *this; }

has just cost me some two hours of debugging. 

The only case where an assignment operator would be NOP is a class without member variables, which this class is evidently not.

If you have to trick the compiler (possibly because of ROOT) into thinking you provided a method which is not actually implemented, the least you could do would be to throw an exception if it was actually called. 

\begin{soapbox}
I feel that in physics, data analysis code is often regarded as a tedious intermediate step between the data and the plots. As long as the plots look fine, who cares about how they were made?

Personally, I feel that this is wrong. Your code is as important a step in the chain of custody from the events to the plots as your detectors are. (So is your DAQ, btw). Buggy code might mess up good data in subtle ways to create wrong plots. And bad code is likely more prone to be buggy, as well. 

(Of course, the incentives for most contributors (e.g. me) do not encourage high quality code. One writes code to create plots for a thesis (e.g. me) or publication. Afterwards, one might create a PR. If merging the PR involved a code review in which people were told to substantially rewrite their code, they probably would not bother. By contrast, in the software industry, programming (and reviewing, and post-review-fixing) is what people are actually paid to do. I have no idea how to fix this: insist on PR merge before thesis acceptance or publication approval? Have someone continuously fix code? Reject half of the PRs and risk fragmenting the project?)
\end{soapbox}

Addendum: 

(0) deleted some unwarranted comparison to life-critical maintenance. (Sorry for that.)

(1) See http://cpp.sh/8n7qv for how this fails. 

(2) I realize that this is endemic: the similar code appears in at least 28 other instances as well. (Further cases promise an assignment operator in the header and do not define it in cxx. Neuland instead deletes unwanted assignment operators. Good for them!) Nevertheless, it is wrong for any reasonable definition of wrong. Of course, this is C++, if one wanted to change the semantics of the assignment operator from "assigns variables" to "does nothing", "compares for equality" ("so users do not have to remember to use =="), or "calls delete on this", we are free to define that. C++ is not in the habit of protecting users from themselves. 

Note that the standard library also relies on operator= obeying certain semantics, the bug which caused this rant was actually that std::sort would refuse to sort a std::vector<Foo>. 

Naturally, C++ is hard enough when one does follow good practices. When actively disregarding these by misusing operator overloads, templates, lambdas or any of the other potential footguns, one is no longer just staying in Gilman House, Innsmouth, but instead rowing out to the Reef at midnight chanting the names of Deep Ones.

**Comment by janmayer** [comment]
> By contrast, in the software industry, programming (and reviewing, and post-review-fixing) is what people are actually paid to do.

Wasn't someone hired recently to do [exactly that](http://institucional.us.es/fnuc/attachments/article/502/18.195_EX_PhD%20Physicist.pdf)?
