### ISSUE TITLE
Geometry file for CALIFA missing

### ISSUE THREAD

**Issue by kresan** [R3BRootGroup/R3BRoot#359]
CI test for CALIFA is failing with error message:
`[FATAL] R3BCalifa: geometry file califa_2020_s444.geo.root not found in standard path`

@gabrigarjim, could you please add it to this repository, or make a fix in R3BRootGroup/macros?

**Comment by gabrigarjim** [comment]
Hi,

I have added the file in a new pull request.

**Comment by kresan** [comment]
Thanks!

Fixed by #360. Closing.
