### ISSUE TITLE
R3BMCTrack crash in Macros

### ISSUE THREAD

**Issue by gabrigarjim** [R3BRootGroup/R3BRoot#363]
Hi,

After the new changes to the R3BMCTrack class and using the proper function calling (GetFourMomentum instead of GetMomentum... etc) I have experienced some crashes in the code when using this object from standard macros as checkResults:

```
Event:0
root.exe(10516,0x116da95c0) malloc: Incorrect checksum for freed object 0x7fda5b9eeeb8: probably modified after being freed.
Corrupt value: 0x0
root.exe(10516,0x116da95c0) malloc: *** set a breakpoint in malloc_error_break to debug_

```
Could anyone take a look to this bug?

Thanks!

**Comment by janmayer** [comment]
Hi, could you post the whole macro(s) to reproduce the bug?

**Comment by gabrigarjim** [comment]
Hi Jan,
The macro I am using is "checkResults.C" in R3BRoot/macros/r3b/califa . We found a workaround by changing the way MCTrack objects are calling when reading events and skipping the delete of that object, so maybe that has something to do with the way this object is deleted....
Thanks!
