### ISSUE TITLE
Make dependency on gtest optional

### ISSUE THREAD

**Issue by kresan** [R3BRootGroup/R3BRoot#376]
@janmayer Do you use gtest? I have just noticed that it is not in nov20 release of FairSoft? Can we make this dependency optional?

**Comment by janmayer** [comment]
FairSoft did install googletest for me.

```bash
$ git status
On branch nov20_patches
Your branch is up to date with 'origin/nov20_patches'.
$ source thisfairsoft.sh
$ spack find
==> 140 installed packages
-- linux-rhel7-sandybridge / gcc@10.2.1 -------------------------
...
googletest@1.10.0  
...
```

**Comment by kresan** [comment]
distribution using Spack is still experimental. The official recommended way is `legacy` using CMake build.

**Comment by janmayer** [comment]
I can check if gtest is available, and ignore the tests if it isn't. However, that is quite a downgrade and should be fixed in FairSoft.

**Comment by kresan** [comment]
Works now, thanks.
