### ISSUE TITLE
Hardcoded loading of boost libraries

### ISSUE THREAD

**Issue by kresan** [R3BRootGroup/R3BRoot#381]
@jose-luis-rs: Can you have a look at `califa/pars/R3BCalifaGeometry.cxx` and take care about following part:
```
// ROOT (or pyroot) is unable to automatically load dependencies of so's for whatever reason.
// so we try to force loading the lib during var initialisation.
// yes, this is ugly.
static bool _dummy_load_libboost_regex = []() {
    char buf[100];
    snprintf(buf, 100, "%s/lib/libboost_regex.so", getenv("SIMPATH"));
    return gSystem->Load(buf);
}();
```
This need to be fixed using dependencies in CMakeLists.txt.

**Comment by janmayer** [comment]
Maybe just adding `Boost::regex` in the CMakeLists.txt will fix it.

```cmake
set(DEPENDENCIES Spectrum R3Bbase R3BData R3BPassive R3BXBall Boost::regex)
```

**Comment by jose-luis-rs** [comment]
Thanks, I did this modification in the CMakeList file:
set(DEPENDENCIES
  Spectrum R3Bbase R3BData R3BPassive R3BTracking **Boost::regex**)
#  Spectrum R3Bbase R3BData R3BPassive R3BTracking **${Boost_REGEX_LIBRARY}**)
because the Boost_REGEX_LIBRARY path is not defined.  I hope it works now.

**Comment by ChristianTackeGSI** [comment]
Just as a reference:

While packaging R3BRoot with spack, I created this patch:
https://github.com/FairRootGroup/FairSoft/blob/9ce43ffcf9212ee3d77d98dea257c260bf0a118f/repos/fairsoft/packages/r3broot/no_boost_loading.patch
And so I wondered, whether this could be applied directly to R3BRoot.

**Comment by jose-luis-rs** [comment]
Yes, I have applied the same modifications and the code works. Thanks!

**Comment by ChristianTackeGSI** [comment]
Commit: https://github.com/R3BRootGroup/R3BRoot/commit/00e4eb6a21e4ec6f1ccb193e28d34df4cb8c7e1b

So from my point of view, this issue can be closed.
