### ISSUE TITLE
Travis is not working

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#387]
Travis is doing nothing with my last PR ??

**Comment by kresan** [comment]
Travis has made changes to its service. I have configured it now. Can you try to force-push to your PR?

**Comment by jose-luis-rs** [comment]
I tried a new PR, but nothing

**Comment by jose-luis-rs** [comment]
I also tried to force-push, but nothing

**Comment by kresan** [comment]
We need to consider moving to a different (self-hosted) CI infrastructure. Travis FREE is available only for limited usage.

**Comment by janmayer** [comment]
Github now has its own CI. Its well integrated into the repository management, and different workflows can be specified, see for example https://github.com/janmayer/hdtv/tree/master/.github/workflows

**Comment by kresan** [comment]
GitHub CI is now enabled for R3BRoot. Closing
