### ISSUE TITLE
Compilation error with gcc-5.1.1, FairRoot(v-15.07a), FairSoft(jul15p1)

### ISSUE THREAD

**Issue by micherciu** [R3BRootGroup/R3BRoot#4]
Hello,

Within this configuration, master or dev of R3BRoot (jul15) doesn't compile ... does it support ROOT 5 ?!

===============================================================================
[ 39%] Built target R3BGfi
[ 39%] Built target libR3BGfi.rootmap
[ 41%] Built target R3BLandDB
[ 41%] Building CXX object land/CMakeFiles/R3BLand.dir/G__R3BLandDict.cxx.o
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,                 fromPATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘ROOT::TGenericClassInfo* ROOTDict::GenerateInitInstanceLocal(const std::vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
       ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4435:68: error: within this context
    static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)
                                                                    ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4437:7: error: within this context
       vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit> *ptr = 0;
       ^
In file included fromPATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4438:69: error: within this context
       static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>),0);
                                                                     ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4441:26: error: within this context
                   typeid(vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>), ::ROOT::DefineBehavior(ptr, ptr),
                          ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4443:26: error: within this context
                   sizeof(vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>) );
                          ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4449:112: error: within this context
       instance.AdoptCollectionProxyInfo( ::ROOT::TCollectionProxyInfo::Generate( ::ROOT::TCollectionProxyInfo::Pushback< vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit> >()));
                                                                                                                ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: At global scope:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit

PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4453:91: error: within this context
    static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)0x0); R__UseDummy(_R__UNIQUE_(Init));
                                                                                           ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void ROOTDict::vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR_Dictionary()’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4457:52: error: within this context
       ::ROOTDict::GenerateInitInstanceLocal((const vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)0x0)->GetClass();
                                                    ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void* ROOTDict::new_vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR(void*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4465:57: error: within this context
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit> : new vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>;
                                                         ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4465:125: error: within this context
       return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit> : new vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>;
                                                                                                                             ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void* ROOTDict::newArray_vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR(Long_t, void*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4468:56: error: within this context
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>[nElements] : new vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>[nElements];
                                                        ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4468:135: error: within this context
       return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>[nElements] : new vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>[nElements];
                                                                                                                                       ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void ROOTDict::delete_vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR(void*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4472:16: error: within this context
       delete ((vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)p);
                ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void ROOTDict::deleteArray_vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR(void*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4475:19: error: within this context
       delete [] ((vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit>*)p);
                   ^
In file included from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.h:46:0,
                 from PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:17:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h: In function ‘void ROOTDict::destruct_vectorlER3BLandDigitizer_CFDcLcLR3BLandDigitizer_CFD_Paddle_HitgR(void*)’:
PATH_TO_WORK/GSI/R3BRoot/source/land/R3BLandDigitizer_CFD.h:58:9: error: ‘struct R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit’ is protected
  struct R3BLandDigitizer_CFD_Paddle_Hit
         ^
PATH_TO_WORK/GSI/R3BRoot/build/land/G__R3BLandDict.cxx:4478:15: error: within this context
       typedef vector<R3BLandDigitizer_CFD::R3BLandDigitizer_CFD_Paddle_Hit> current_t;
               ^
land/CMakeFiles/R3BLand.dir/build.make:827: recipe for target 'land/CMakeFiles/R3BLand.dir/G__R3BLandDict.cxx.o' failed
make[2]: *** [land/CMakeFiles/R3BLand.dir/G__R3BLandDict.cxx.o] Error 1
CMakeFiles/Makefile2:1521: recipe for target 'land/CMakeFiles/R3BLand.dir/all' failed
make[1]: *** [land/CMakeFiles/R3BLand.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by kresan** [comment]
Hello,

R3BRoot is currently not compatible with gcc 5.x
I will resolve this issue next week.

Best regards,
Dima

**Comment by kresan** [comment]
Hello Madalin,

unfortunately I can not reproduce your problem. Which version of R3BRoot do you mean? And version of ROOT? Your compilation error is looking like you are compiling master branch with ROOT 6. But your issue description states different.

**Comment by micherciu** [comment]
Hi Dima,

I checked again the configuration and I use FairRoot (v-15.07a), FairSoft (jul15p1, without compilation of ROOT6, just ROOT5) and the recent R3BRoot tag(42f919c) - I quess jul15.

Best regards

**Comment by kresan** [comment]
Could you try with dev branch, please.

Cheers,
Dima

**Comment by micherciu** [comment]
Unfortunately, the same error exist ...

**Comment by micherciu** [comment]
probably this may help ... the configuration file for R3BRoot I have ...

------------------------------------------------------------------------------------------------------------------------------

-- The C compiler identification is GNU 5.1.1
-- The CXX compiler identification is GNU 5.1.1
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- NOT Found FAIRBASE
-- Setting FairRoot environment…
-- FairRoot ... - found Madalin/root/GSI/FairRoot/install
-- FairRoot Library directory  :     Madalin/root/GSI/FairRoot/install/lib
-- FairRoot Include path…      :     Madalin/root/GSI/FairRoot/install/include
-- FairRoot Cmake Modules      :    Madalin/root/GSI/FairRoot/install/share/fairbase/cmake
-- Performing Test _HAS_CXX11_FLAG
-- Performing Test _HAS_CXX11_FLAG - Success
-- Checking C++11 support for "__func__"
-- Checking C++11 support for "__func__": works
-- Checking C++11 support for "auto"
-- Checking C++11 support for "auto": works
-- Checking C++11 support for "auto_ret_type"
-- Checking C++11 support for "auto_ret_type": works
-- Checking C++11 support for "class_override_final"
-- Checking C++11 support for "class_override_final": not supported
-- Checking C++11 support for "constexpr"
-- Checking C++11 support for "constexpr": works
-- Checking C++11 support for "constructor-delegation"
-- Checking C++11 support for "constructor-delegation": works
-- Checking C++11 support for "cstdint"
-- Checking C++11 support for "cstdint": works
-- Checking C++11 support for "decltype"
-- Checking C++11 support for "decltype": works
-- Checking C++11 support for "initializer_list"
-- Checking C++11 support for "initializer_list": works
-- Checking C++11 support for "lambda"
-- Checking C++11 support for "lambda": works
-- Checking C++11 support for "long_long"
-- Checking C++11 support for "long_long": works
-- Checking C++11 support for "nullptr"
-- Checking C++11 support for "nullptr": works
-- Checking C++11 support for "regex"
-- Checking C++11 support for "regex": works
-- Checking C++11 support for "rvalue-references"
-- Checking C++11 support for "rvalue-references": works
-- Checking C++11 support for "sizeof_member"
-- Checking C++11 support for "sizeof_member": works
-- Checking C++11 support for "static_assert"
-- Checking C++11 support for "static_assert": works
-- Checking C++11 support for "variadic_templates"
-- Checking C++11 support for "variadic_templates": works
-- Checking C++11 support for "sharedpointer"
^[[B-- Checking C++11 support for "sharedpointer": works
-- fairsoft-config found
--- Found a Linux ssytem
--- Found GNU compiler collection
--- Build Type: RelWithDebInfo
--- Compiler Flags:  -std=c++11 
-- Looking for Boost ...
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   timer
--   program_options
Building without dbase ...
-- Looking for Root...
-- Looking for Root... - Found Madalin/root/GSI/Fairsoft/jul15p1/build/bin/root
-- Looking for Root... - Found version is 5.34/33 
-- Looking for GEANT3...
-- Looking for GEANT3... - found Madalin/root/GSI/Fairsoft/jul15p1/build/lib64/libgeant321.so
-- Looking for GEANT4...
-- Looking for GEANT4... - found Madalin/root/GSI/Fairsoft/jul15p1/build/lib
-- Looking for GEANT4 DATA files...
-- Found G4EMLOW data
-- Found PhotonEvaporation data
-- Found G4NDL data
-- Found G4NEUTRONXS data
-- Found G4PII data
-- Found RadioactiveDecay data
-- Found RealSurface data
-- Found G4SAID data
-- Looking for GEANT4VMC...
-- Looking for GEANT4VMC... - found  Madalin/root/GSI/Fairsoft/jul15p1/build/lib
-- Looking for VGM...
-- Looking for VGM... - found  Madalin/root/GSI/Fairsoft/jul15p1/build/lib
-- Looking for CLHEP...
-- Looking for CLHEP... - found Madalin/root/GSI/Fairsoft/jul15p1/build/lib
-- Looking for Java...
-- Could NOT find Java (missing:  Java_JAR_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAVAH_EXECUTABLE Java_JAVADOC_EXECUTABLE) (found version "1.8.0.51")
-- Looking for Java... - found /usr/bin/java 
-- Looking for Perl...
-- Found Perl: /usr/bin/perl (found version "5.20.2") 
-- Looking for Perl... - found /usr/bin/perl 
-- Looking for Rule Checker...
-- Looking for Rule Checker... - No Rules found
-- Looking for Rule Checker... - Not found 
running /bin/chmod u+x  Madalin/root/GSI/R3BRoot/build/macros/r3b/r3bsim.sh  2>&1
running /bin/chmod u+x  Madalin/root/GSI/R3BRoot/build/macros/r3b/califa/califasim.sh  2>&1
running /bin/chmod u+x  Madalin/root/GSI/R3BRoot/build/macros/elise/elsim.sh  2>&1
Build the eventdisplay.
-- Configuring done
-- Generating done

----------------------------------------------------------------------------------------------------------------------------

**Comment by micherciu** [comment]
after a correct switch to dev branch:
git checkout branch dev
and 
git pull origin dev
 
now it compiled ok ... thank you
