### ISSUE TITLE
CMake Failed

### ISSUE THREAD

**Issue by swyellow** [R3BRootGroup/R3BRoot#417]
Hi, after I installed FairSoft and FairRoot successfully, I had a problem with the CMake step in R3BRoot which gives the error below : 
(PC system : Ubuntu 20.04;  gcc 9.3.0; cmake 3.16.3; FairSoft apr21; FairRoot v18.2.0-349-gfae563fdf;
R3BRoot may21-4-g82ade09b)

#-- Could not find FairCMakeModules. It is recommended to install https://github.com/FairRootGroup/FairCMakeModules
-- Setting FairRoot environment:
--   FairRoot prefix            : /home/s034/fair_install/FairRootInst
--   FairRoot Library directory : /home/s034/fair_install/FairRootInst/lib
--   FairRoot Include path      : /home/s034/fair_install/FairRootInst/include
--   FairRoot Cmake Modules     : /home/s034/fair_install/FairRootInst/share/fairbase/cmake
CMake Error at CMakeLists.txt:104 (find_package2):
  Unknown CMake command "find_package2".

-- Configuring incomplete, errors occurred!

By the way, my installation method is:
`mkdir ~/R3BRoot_install`
` cd  ~/R3BRoot_install`
`git clone https://github.com/R3BRootGroup/R3BRoot.git`
`cd R3BRoot`
` git checkout dev`
` git clone https://github.com/R3BRootGroup/macros.git`
` mkdir ../build`
`cd ../build`
`export SIMPATH=~/fair_install/FairSoft_src/install`
` export FAIRROOTPATH=~/fair_install/FairRootInst`
`cmake ../R3BRoot/`

Can anybody help me? Thank you so much in advance.
[CMakeOutput.log](https://github.com/R3BRootGroup/R3BRoot/files/6520630/CMakeOutput.log)
[CMakeLists.txt](https://github.com/R3BRootGroup/R3BRoot/files/6520632/CMakeLists.txt)

**Comment by jose-luis-rs** [comment]
Please, try to do this:
git clone https://github.com/R3BRootGroup/macros.git
cd macros
git checkout dev

**Comment by kresan** [comment]
@swyellow R3BRoot may21 is working only with FairSoft `jun19p2` and FairRoot `v18.2.1`. We are currently working on dev branch of R3BRoot being compatible with the latest FairSoft and FairRoot, but this is not finished yet.
Please report back whether this solves your issue.

**Comment by swyellow** [comment]
> @swyellow R3BRoot may21 is working only with FairSoft `jun19p2` and FairRoot `v18.2.1`. We are currently working on dev branch of R3BRoot being compatible with the latest FairSoft and FairRoot, but this is not finished yet.
> Please report back whether this solves your issue.

@kresan Thank you for the information. I tried the version you mentioned. Although at first had the similar error in https://github.com/FairRootGroup/FairSoft/issues/339 and solved it by modifying tools/rootconfig.sh. Then I can successfully install the FairSoft (jun19p1-1-gfa300fb), FairRoot (v18.2.1) and R3BRoot (may21-4-g82ade09b) without any error. 

However, when I try to run a simulation with run_sim.C, I get problems.
The full output log and corresponding config.sh is attached. I guess some path are 
[Log.txt](https://github.com/R3BRootGroup/R3BRoot/files/6526854/Log.txt)
[config.txt](https://github.com/R3BRootGroup/R3BRoot/files/6526855/config.txt)

wrong. Can you give some advice?

`mkdir ~/R3BRoot_install`
`cd  ~/R3BRoot_install`
`git clone https://github.com/R3BRootGroup/R3BRoot.git`
`cd R3BRoot`
`git checkout dev`
`git clone https://github.com/R3BRootGroup/macros.git`
`cd macros`
`git checkout dev`
`mkdir ../../build`
`cd ../../build`
`export SIMPATH=~/fair_install/FairSoft_src/install`
`export FAIRROOTPATH=~/fair_install/FairRootInst`
`cmake ../R3BRoot/`
`make`


Simulation check
`cd build`
`. ./config.sh`
`cd ../R3BRoot/macros/r3b/`
`root -l run_sim.C`

**Comment by swyellow** [comment]
@kresan Thank you for the information. I tried the version you mentioned. Although at first I had the similar error in https://github.com/FairRootGroup/FairSoft/issues/339 and solved it by modifying tools/rootconfig.sh. Then I can successfully install the FairSoft (jun19p1-1-gfa300fb), FairRoot (v18.2.1) and R3BRoot (may21-4-g82ade09b) without any error. 

I already can create sim.root and par.root from run_sim.C. Then I run eventDisplay.C which ends with error and when I close the Eve Main Window by clicking "x" from the right panel, root would always crash. Is this a bug or I miss something?  You can check the log in the attachment.
Can you give some advice?

FairSoft installation:
compiler=gcc
debug=no
optimize=no
build_MQOnly=no
geant4_download_install_data_automatic=yes
geant4_install_data_from_dir=no
geant4mt=yes
build_root6=yes
build_python=no
install_sim=yes
SIMPATH_INSTALL=/home/s034/fair_install/FairSoftInst
platform=linux
geant4 compile in single threaded mode


After FairRoot, before R3BRoot, step I added in .bashrc:
`export ROOTSYS=~/fair_install/FairSoftInst`
`export PATH=$PATH:$ROOTSYS/bin`
`source ~/fair_install/FairSoftInst/bin/thisroot.sh`


My installation method 
`mkdir ~/R3BRoot_install`
`cd  ~/R3BRoot_install`
`git clone https://github.com/R3BRootGroup/R3BRoot.git`
`cd R3BRoot`
`git checkout dev`
`git clone https://github.com/R3BRootGroup/macros.git`
`cd macros`
`git checkout dev`
`mkdir ../../build`
`cd ../../build`
`export SIMPATH=/home/s034/fair_install/FairSoftInst`
`export FAIRROOTPATH=/home/s034/fair_install/FairRootInst`
`cmake ../R3BRoot/`
`make`


Simulation check
`cd build`
`. ./config.sh`
`cd ../R3BRoot/macros/r3b/`
`root -l run_sim.C`

**Comment by kresan** [comment]
Do you see the detectors in the event display, despite the error message? If yes, these errors can be ignored.

It is "normal" behaviour when you try to close clicking on x. The recommended way to exit from event display is to type `.q` in ROOT command line.

**Comment by swyellow** [comment]
> Do you see the detectors in the event display, despite the error message? If yes, these errors can be ignored.
> 
> It is "normal" behaviour when you try to close clicking on x. The recommended way to exit from event display is to type `.q` in ROOT command line.

I understand. Thank you so much.
Now there is no problem.

**Comment by kresan** [comment]
Thanks for feedback. Closing.
