### ISSUE TITLE
Vote/Proposal: make dev the default branch

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#427]
Our default branch is master, last updated in 2017. I propose we make dev the default branch instead. 

Reasoning: 
The default branch is what users see when they first browse the repository on github, or naively clone the repo. What they want in 99% of the cases is the latest trunk version, which is dev. At the moment, we are misleading causal observers to think that R3BRoot has not been under development since 2017, as well as confusing Newbie users (and distracted users who should know better, such as myself sometimes.)

FairRoot uses this dual branch system, but I would argue that their project is fundamentally convergent: while new features might still be added, there will be little reasons to do big changes in the existing code base. Also, they have the manpower to actually do regular releases: the last substantial changes to master seem to be some 3-4 month ago.
For R3BRoot, the situation is fundamentally different. For the foreseeable future, we will always have one more beam time with a new or changed detector. Always a moving target. "R3BRoot: the definite version" is not going to happen -- and that is okay. 

Comparison to popular open source projects:
linux: https://github.com/torvalds/linux default=master seems to be the bleeding edge
gimp: https://gitlab.gnome.org/GNOME/gimp same
Apache: https://svn.apache.org/repos/asf/httpd uses svn internally, so their default branch is called trunk, otherwise same
ROOT: https://github.com/root-project/root same

In a nonbinding vote (e.g. Wikipedia Meinungsbild style), I hearby ask the contributors to state their preference for or against this proposal. :-)

(A more difficult issue to solve is the mixture of beamtime-dependent and experiment-independent code. I think that for analysing older beamtime data, many prefer an unofficial fork of the R3BRoot dev as it was shortly after the experiment. I think this is unfortunate, as this means that neither will upstream get any bug fixes they do, nor will they get any bugfixes from upstream. In the present system, most R3BRoot devs get paid for (or earn their degrees by) doing data analysis, not to write good code and commit it. They are typically willing to make a PR when their analysis is done, but have no great incentive to do so when it is complicated as in "figure out which local commits to my 2019 fork are not experiment-dependent but general useful and figure out how to cherry-pick them into the latest dev version for a PR". I predict this divergence will get greater in time. 

One option would be to include plenty of tests for each beam time, e.g. saying "from this day forward, R3BRoot should support 2019-s444 forever". Another option would be to accept that divergences are going to happen and just create branches for every experiment with significant changes to any detectors. 

Of course, all of this is just hearsay from my part, for all I know, the current version still handles S438b perfectly.)

**Comment by janmayer** [comment]
I fully agree that the current master branch has no use. In addition, the current repository has [way too many branches](https://github.com/R3BRootGroup/R3BRoot/branches) (some already called “stale” by GitHub) – I think most, if not all, should be deleted, and the current `dev` should be the new `master` and the only branch in the repository. If there are issues, fix and fail forward: "Vorwärts immer, rückwärts nimmer."

In addition, an extremely important change that I think is necessary is to fully disconnect the macro directory. Currently, one needs to manually download it to the repository for no good reason. There are some tests in this repo that are required to build and test the system, but they should not be in this directory in the first place – but either in `/tests/` or `/<detector>/tests` where they belong. There are also way too few tests 😉.

As you have pointed out, that might introduce a challenge to keep the code working for all older experiments. This is especially critical to be able to reproduce results. (Note this also requires that *everyone* commits the code they use to get their results.) I hope that can be solved by having a "macro-repository" for each experiment – each of which could include an experiment-specific test or even a full analysis routine to ensure everything still works. This experiment-analysis macro directory should then be placed outside the R3BRoot directory at the users end to keep them separate, clean, and thus easily commit- and pull-able.

**Comment by hapol** [comment]
Regarding using dev as the default branch, I agree. I also agree that old unused branches should be removed but we could tag a few versions just to remind the status during some experiments, if we agree that this could be useful.

The reason to separate macros (if I remember correctly) was related to the tests. Maybe @kresan  could remind about it and if it can be solved by moving things around. Separating macros have created some small problems of synchronisation, which also could happen with other independent repositories, SOFIA for instance (when modifications in SOFIA require also modifications on the R3BRoot code to be compatible).

Regarding the experiment-specific macros, parameters, geometries, simulations and in general, anything that is specific to a given experiment: there is an ongoing development based on a private repository per experiment. The idea behind this development: parameters change at different timestamps (events) and there must be a procedure for merging parameters which enters in the analysis/simulation with the modification of the runId at the corresponding timestamp, when unpacking the event. Then, a single ROOT file with all the parameters would contain the complete set of parameters and changing from one parameter set to another would be taken by the framework. Additionally all macros, geometries, ... will be separated in the corresponding folders of these experiment-specific private repositories. A template repository is being setup and an example for S455/SOFIA will be ready soon. I think the approach follows what @janmayer has said in the last paragraph.

R3BRoot should only keep the common code and common/template macros for analysis and simulation for each detector and for common systems (correlations).  Anything related-specific should go to the private repositories. And I still think that the R3BRoot should work with backwards compatibility for 2019 experiments till now... If this has to be broken in the future, we should fix a version before for backwards compatibility ... and if this already happen, please, report to fix it!

**Comment by kresan** [comment]
The `master` branch is updated roughly 1 time per year. The last merge and release was on May 12 2021. Before that - August 2019. The effect that you have observed is that master branch was accidentally forced pushed to the older state. I have fixed it now.
We will still continue with the current scheme, at least for the period of transition to FairRoot v19.0.0, where the backward compatibility will be completely broken.
I will clean up the stale branches.

**Comment by klenze** [comment]
ok
