### ISSUE TITLE
Proposal: make data containers structs (inheriting from TObject)

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#433]
From my understanding of good C++, classes are appropriate when there are [invariants](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-struct). 

This is generally not the case for the stuff residing in r3bdata.

Furthermore, this leads to constructor calls with many parameters, as in:
 new ... R3BCalifaPoint(trackID, detID, ident, posIn, momIn, time, length, eLoss, Nf, Ns, EventId);

Unlike Python, C++ does not allow named parameters (But the authors of the eight-parameter TH2D constructors are [proposing to add them](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0671r2.html)). For now, order matters, and no reader will ever know if eLoss comes before or behind Ns and Ns. 

While [aggregate instantiation (3-4)](https://en.cppreference.com/w/cpp/language/aggregate_initialization) could eventually be used with structs (which would have to be TObject wrapped by some template magic), I do not think we will adopt C++20 before FAIR starts. :-(

For now, I would propose:
* making member variables public if there are no invariants
* default-setting them: uint32_t foo{};
* instantiating the struct with default values, then setting the members.

 struct R3BFoo: public TObject
 {
    uint32_t bar{};
    uint64_t baz{};
    // ...
    ClassDef...
 };
 // when constructing
 auto obj=new R3BFoo();
 obj.bar=myBar;
 obj.baz=myBaz;

This way, the causal reader can check that the the bar and baz fields are indeed not switched.

**Comment by hapol** [comment]
Moving from class to structure is a quite large modification, producing a change in the data structure to be stored in the TTrees and a departure from what other collaborations (and FairRoot team) are doing. I cannot see the benefit (class and struct are the same, with some different default settings, in c++), and I can see some problems if you need to create "invariants", any constrain on the data in the constructor, which could be the case.  I would also prefer private datamembers always, where modifications cannot slip in the code without an explicit Set function. 

For the second part of the proposal, I generally agree with any modification that enforces good use and reduces the possibility of mistakes. I would consider strange that the developer do not check the constructor to call it (and therefore check the order) but anyway any procedure to reduce mistakes is welcome.

**Comment by klenze** [comment]
If ROOT containers would support templates, the obvious solution would be to make the R3BFooData things const when fetched from the TClonesArray. 

For now, I have autogenerated Getters based on a sed script I put into a comment. It would be trivial to add Setters as well, but I do not feel they are really required. Typically the data containers are generated by exactly one class (in r3bsource or califa/calibration), and that one class could be a friend of the data class. Allowing world+dog to change members nilly-willy seems overkill to me, and exactly that is the message you send if you have public setters.

(For testing purposes, it might be required to manually create data objects. Here, a workaround might be to make the members accessible if a specific preprocessor macro is defined. Ugly.)

**Comment by janmayer** [comment]
The biggest problem is the strong dependency on TObject. With it, the data classes will sadly never be Plain-Old-Data objects which they should be.

You can, of course, make the member variables public and forego all the getters and setter - and be very close to a struct. That would safe a lot of code.
