### ISSUE TITLE
C++17 support?

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#435]
I would argue for going to -std=c++17.

Most of our lx* boxes run Debian, so I will make the case for Debian.
Debian [buster](https://www.debian.org/releases/buster/) was released more than two years ago. It features [gcc 8](https://packages.debian.org/buster/gcc), which [fully supports](https://gcc.gnu.org/projects/cxx-status.html#cxx17) C++17. 

While lxir136 still runs stretch (and to my dismay, some computers in in the counting house still run jessie!), I think of that as a reason to dist-upgrade (for security, if nothing else), not as a reason to keep the standard at the level it was a decade ago. 

(A Debian fanboi myself, I will also note that Debian stable is not exactly the cutting edge. So if gcc 8 has been in stable for two years, we can be rather sure that it will also be present in all other widely used distributions.)

One alternative would be to add a recent compiler to FairSoft. FairSoft [already provides](https://github.com/FairRootGroup/FairSoft/tree/dev/repos/fairsoft-backports/packages) versions of CMake, Perl, Boost and Python so why not gcc 12 as well? Or clang-12, if someone can figure out how to compile ROOT using that. Then we could directly go for C++20. 

It should be noted that rootcint does not seem to have a flag to specify a C++ standard, it seems to use whatever root was compiled with. So departing from C++11 will require FairSoft (or at least ROOT) and FairRoot to be compiled with that flag as well.

**Comment by kresan** [comment]
I have nothing against moving to C++ 17. Newest FairSoft and FairRoot support it already.
The only problem is the Debian 8 on lxi* with gcc 4.9. The issue with upgrading to Debian 10 is initiated and ongoing, but there is no statement when it will happen. Let's keep an eye on it.
