### ISSUE TITLE
Build fails: cannot find -lR3BLandDB

### ISSUE THREAD

**Issue by janmayer** [R3BRootGroup/R3BRoot#5]
Building a fresh dev clone fails with:

```
Scanning dependencies of target R3BDB
Linking CXX shared library ../../lib/libR3BDB.so
/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: cannot find -lR3BLandDB
```

`landdb` was commented out in `r3bdb/CMakeLists.txt`
https://github.com/R3BRootGroup/R3BRoot/commit/a37c9d56d79f1d3148be26a831beeaaf17fa25f1#diff-5839202420d9f765da9c1938289b795c .

I'm using FairSoft (master), FairRoot (master) with dbase (master).

**Comment by kresan** [comment]
This commit 9f54db0 should solve the issue. Please rebase from main dev branch, and recompile.

**Comment by janmayer** [comment]
Solved, thank you.
