### ISSUE TITLE
Where do I post problems?

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#505]
### Where to write issues?

I've been working with R3BRoot since April 2021, and I am now at GSI working with the experiments. I saw that the [R3BRoot](www.r3broot.gsi.de) website does not exist anymore, that is a shame. I also have seen that fortunately the [GSI Forum](https://forum.gsi.de/index.php?rc=Done) still exists. 

I'm a bit confused on how to act when I have questions for R3BRoot, should I add them here or on the forum? People in GSI normally just ask other elements but as you may understand, because this is a multinational collaboration, those issues should be public and anyone that runs into the same problems should be informed. In the future this will save everyone some time.

### How to write issues? (if they are supposed to be here on Git)

In the future, if I want to write an issue, what information should I add at the beginning of my post? There are a lot of R3BRoot versions and people run it from different operating systems (I think everyone should do it through docker but that's another thing).

I hope this starts to change because it would be great that we can all profit from this simulation and analysis tool!

**Comment by jose-luis-rs** [comment]
This is the right place, please use it.

For R3BRoot, use always the latest version from the dev branch.

Cheers

**Comment by tcsousa99** [comment]
Dear @jose-luis-rs,

Thank you for your response. Do you know what happened to R3BRoot website and my second question was on rules for posting things here, what information do we put before posting?
