### ISSUE TITLE
Fibers: Hit-Level calibration

### ISSUE THREAD

**Issue by enlorenz** [R3BRootGroup/R3BRoot#541]
Regarding Fiber (30-33) calibrations:

For Cal-Level: We have the Mapped2Cal class as well as the Mapped2CalPar class to generate parameters.
For Hit-Level: We have Cal2Hit class to read parameters, but I can't seem to find the class to generate Hit-level parameters. Are these classes/functions hidden somewhere else, or are they non existent at all?

**Comment by jose-luis-rs** [comment]
I think that the parameters are calculated inside the class R3BBunchedFiberCal2Hit_s494, with this constructor:

R3BBunchedFiberCal2Hit_s494(const char* a_name,
                                                         Int_t a_verbose,
                                                         enum R3BTCalEngine::CTDCVariant a_ctdc_variant,
                                                         Direction a_direction,
                                                         UInt_t a_sub_num,
                                                         UInt_t a_mapmt_per_sub,
                                                         UInt_t a_spmt_per_sub,
                                                         Bool_t a_is_calibrator,
                                                         Bool_t a_is_gain,
                                                         Bool_t a_is_tsync)

From your analysis macro you should set "a_is_calibrator" true, and false if you already have a file with the calibration parameters.

The parameters are calculated in the function:
R3BBunchedFiberCal2Hit_s494::FinishTask()
