### ISSUE TITLE
Event Header Ambiguity

### ISSUE THREAD

**Issue by ManuelXarepe** [R3BRootGroup/R3BRoot#544]
Hans and I got a root file after Cal2HIt with two event headers. We looked into the R3BRoot code and found that the lifetime and owner of the R3BEventHeader is not well defined, it even leaks into the macros. Could someone please have a look?

**Comment by jose-luis-rs** [comment]
This is the usual definition for the EventHeader in the online macros:

   // Create online run ------------------------------------
   FairRunOnline* run = new FairRunOnline();
   R3BEventHeader* EvntHeader = new R3BEventHeader();
   run->SetEventHeader(EvntHeader);
   run->SetRunId(1);
   run->ActivateHttpServer(refresh, port);

But, what are you doing exactly? Are you using the online macro?

**Comment by ManuelXarepe** [comment]
In this case, I produced root files with HIT-level data that I want to analyze using root offline. This Hit level data includes RPC, and Los, with both off and On Spill data. I wanted to use TPat to choose the on spill events, but when I do this my code explodes. Thats when we started to dig into the why it was exploding and found what i described in the problem.

**Comment by jose-luis-rs** [comment]
Please, could you add a photo of what you see in your TBrowser after open the root file?

**Comment by jose-luis-rs** [comment]
I have sent you the online macro to produce the root file with all the data. Please, update it in github and comment here where was the mistake. Thanks in advance.

Enclosed one picture showing the eventheader and the tclonearrays that you should see after running the macro.

![rpc_root](https://user-images.githubusercontent.com/18137822/162584345-73add644-1330-4a35-ae71-f122e1a18b1e.png)

**Comment by ManuelXarepe** [comment]
I will try with the macro you sent. I attach a print of the output of running evt->print() in one of the root files i created with my macro.  you can see there that i have two event Headers in the same evt.
![Capture](https://user-images.githubusercontent.com/83393627/162588553-4a38a70c-3464-44ff-9c01-dd5af08365a2.PNG)

**Comment by jose-luis-rs** [comment]
Hello

I have solved this problem in my last PR [https://github.com/R3BRootGroup/R3BRoot/pull/547](url), the initialization was in the wrong position. 

Now we can also use the R3BTrloiiTpatReader class to put conditions on the output root file, these are the relevant lines of code:

  R3BUcesbSource *source = new R3BUcesbSource(filename, ntuple_options, ucesb_path, &ucesb_struct,
                                                                                                                                        sizeof(ucesb_struct));
  source->SetMaxEvents(nev);

  // Definition of reader ---------------------------------
  // Add readers ------------------------------------------
  source->AddReader(new R3BUnpackReader(&ucesb_struct.unpack,
                                        offsetof(EXT_STR_h101, unpack)));
  auto unpacktrloii = new R3BTrloiiTpatReader(&ucesb_struct.unpacktpat, offsetof(EXT_STR_h101, unpacktpat));
  unpacktrloii->SetTrigger(1);
  unpacktrloii->SetTpatRange(4,4);
  source->AddReader(unpacktrloii);

with the lines:
  unpacktrloii->SetTrigger(1);
  unpacktrloii->SetTpatRange(4,4);
you can select the trigger and the tpat, in this case tpat=4.

If you want to select a range of tpats, for instance from tpat=2 to tpat=16
  unpacktrloii->SetTrigger(1);
  unpacktrloii->SetTpatRange(2,16);

Let me know if this works!

**Comment by jose-luis-rs** [comment]
I think that this was solved.
