### ISSUE TITLE
Access to the Tpat/Trigger values from EventHeader

### ISSUE THREAD

**Issue by bzhantoine** [R3BRootGroup/R3BRoot#546]
Hello everyone,

To analyze the FOOTs data taken during the beam test, I would like to make a selection on the Tpat values.
I know how to access information from the branches in TCloneArray (Mapped, Cal and Hit Data for detectors) but not from the EventHeader. I already searched in some online codes, for example R3BFootOnlineSpectra.cxx .

I extracted the root files from the lmd files in 2 ways: with the _unpacker.C_ code so with all the Tpat values, and with _online codes_ : /u/land/r3broot/202205_s522/foot/R3BRoot_dev/online/online_foot.C and /u/land/r3broot/202205_s522/foot/macros/online/online_foot.C .

I tried to select a specific Tpat value by using the _online code_ but that failed so far: all events (from the lmd file) are present in the root files produced by this code, all Tpat have a unique value ( = 0) and this whatever the selected Tpat value.

On the other hand, I tried to select in the produced root files (with the _unpacker.C_ code) a specific Tpat value by starting my attempts with the lines found in the OnlineSpectra code, but my macro crashes (*** Break *** segmentation violation ) when reaching the first new line (I checked that with cout command) :

"
 FairRootManager* mgr = FairRootManager::Instance(); 
     if (NULL == mgr)
                     LOG(fatal) << "FairRootManager not found";

    int tpat_;
    R3BEventHeader* header;
    header = (R3BEventHeader*)mgr->GetObject("R3BEventHeader");
    if (!header)
            header = (R3BEventHeader*)mgr->GetObject("EventHeader.");

    tpat_ = header->GetTpat();
"

Thank you in advance for your help.

**Comment by gabrigarjim** [comment]
Hi Antoine ,
First of all be sure that in your unpacking macro you are calling the reader that unpacks TPat information :
 ```
      source->AddReader(new R3BTrloiiTpatReader(
      &ucesb_struct.unpacktpat, offsetof(EXT_STR_h101, unpacktpat)));
```
Then get it in a proper way ,
```
     TBranch  *tpatBranch = eventTree->GetBranch("EventHeader.");
     R3BEventHeader *fEventHeader;
     tpatBranch->SetAddress(&fEventHeader);
```

and read it in the main event loop :
 ```
Int_t fTpat, tpatbin;

if (fEventHeader->GetTpat() > 0)
     {
         for (Int_t i = 0; i < 16; i++)
         {
             tpatbin = (fEventHeader->GetTpat() & (1 << i));
             if (tpatbin != 0){
                 fTPat=i+1;
                }
             }

cout<<"TPat for event "<<j<<" : "<<fTPat<<endl;
```

Hope this helps.

**Comment by bzhantoine** [comment]
Thank you for your answer.
The unpacker was already fine (path =/u/land/r3broot/202205_s522/R3BParams_S522/macros/exp/unpack/unpack_data.C ) and my macro, after adding your lines,  doesn’t crash anymore but the Tpat values returned by fEventHeader->GetTpat() are never > 0 but still = -1382216307 , so I couldn't enter in the loop you gave me.

(if someone want to use these lines, there is a little mistake:  GetBranch("EventHeader**.**");  =>  GetBranch("EventHeader");

**Comment by bzhantoine** [comment]
Actually, I removed this dot because when I used it, my macro crashed when it reached "tree->GetEntry(i)", right at the beginning of my loop.

I use the following macro:
/u/land/r3broot/202205_s522/foot/macros/offline/WorkingDir/Antoine/analysis_Antoine_Gsi.C
(the root file are in the same folder)

Thank you in advance for your help.

**Comment by gabrigarjim** [comment]
Hi, just put in that folder a couple of macros, the one you sent working and other one with general procedures for tpat analysis. I did not see anything wrong about the way you were getting the tpats but it was crashing, so I just rewrite the same stuff and it started working (I suppose there were some extra stuff coming from copying -pasting.... this I have to check ). Anyways, some remarks :

1. /u/land/r3broot/202205_s522/ is a place for parameter development and tracing. User stuff should be placed on your folder in land and then commited to this repository (but definitely not in a folder called "Antoine". I can send you the proper scheme for this repository)
2. I saw some .dat files with pedestals. This pedestals should go in a .par file that is loaded to fill a proper container. Please do not use .dat files or similar to hardcode parameter management.
3. As a general recommendation : clear TCloneArray at the beggining of the eventloop (FootMappedData, in your case)

If you need help please don't hesitate to ask.

**Comment by bzhantoine** [comment]
Thank you again for your help.

I ran the macro with your changes and it crashed, but by adding the two lines you used in tpat_study.C it finally works.
I deleted these two lines from tpat_study.C and it crashed as well.

They were these: 
eventTree->SetBranchStatus("*",0);
eventTree->SetBranchStatus("EventHeader.*",1);
(before the TBranch line)

Regarding your remarks (1 and 2), during the analysis meetings organized by Valerii Panin, we were made aware of it.
I use the .dat file (there is also a .par file in the folder) and I work in this folder only during the test phase.

**Comment by gabrigarjim** [comment]
In principle this should not be necessary
`eventTree->SetBranchStatus("*",0);
eventTree->SetBranchStatus("EventHeader.*",1);`
as they have to be _on_ when you open a root tree. I will take a look to this.... maybe is related to what is happening to @ManuelXarepe
