### ISSUE TITLE
Development in VSCode 

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#550]
Dear @hapol,

This is not an "issue" in itself but just a quick note that can save time for a lot of people that use IDE's like VSCode to develop R3BRoot and I think it could be added to the wiki as a simple note (I don't mind writing it), just need your authorization.

When writing the name of a class like "R3BCalifaCrystalCal2Hit" it would be pretty good to have an auto completion tool, and by just adding a simple .json file to the .vscode directory like this, allows for people to have the Fair and R3B Classes to be auto completed and that helps a lot while developing.
```

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/home/teetos/Programs/FairRoot/**",
                "/home/teetos/Programs/FairSoft/**",
                "/home/teetos/Programs/R3BRoot/**"

            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

I know it is a minor detail but it think we can improve the wiki bit by bit :)

Kind regards,

**Comment by hapol** [comment]
Thanks a lot, @tcsousa99 ! I'm personally not using IDE's for developing, but adding this kind of information would help for others with a similar environment. Feel free to add the information in the wiki (I guess everyone in the project has authorization for adding the information).

**Comment by tcsousa99** [comment]
Added the page to the wiki :)
