### ISSUE TITLE
Use several instances of the same detector in simulations

### ISSUE THREAD

**Issue by acorsi** [R3BRootGroup/R3BRoot#552]
Hello, I am trying to use several instances of fibers (fi11) in a simulation, get several branches in the sim.root file, but only the first one is filled, ie Fi11Point_1 is filled but not Fi11Point_2. Is there another way to use the constructor to prevent such issue? below is my current version in the run_sim.C macro.
run->AddModule(new R3BFi11("doublebig_fi11.geo.root", {fi10pos.X(), fi10pos.Y(),fi10pos.Z()}, {"" ,9    0.0,90-angle,0.0}));

Thank you in advance. Cheers,
Anna

**Comment by hapol** [comment]
Hi Anna,
it is not possible to instantiate twice the same detector in two locations. To my understanding there is a single kDetector identifier and energy losses in any of the two objects will fill the same data structure. You should use a different detector (another fiber set)... or modify the code heavily (data structure should be modified to add a detector instance; ProcessHit() should be able to assign the detector instance based on the GEANT volume name, ...). I would recommend to use another similar detector; I do not see other easy solution.
Hope it helps. Cheers

**Comment by acorsi** [comment]
Hi Hector, I see. The question arises for fibers, and it seems to me that all fibers/fi* classes are very similar (right?) so maybe this is the easy solution, use different ones for different instances. Thanks! Anna
