### ISSUE TITLE
Fiber online task

### ISSUE THREAD

**Issue by enlorenz** [R3BRootGroup/R3BRoot#553]
It seems to me, that the current online task for the fibers is the s494 one. Is that correct? Or did I just not find the s522 FiberOnline task?

**Comment by jose-luis-rs** [comment]
The new code is in my last pull request:
https://github.com/R3BRootGroup/R3BRoot/pull/551
but you have to wait for the merge. 
The new online class for fibers will be:
R3BRoot/fiber/online/R3BFiberMAPMTOnlineSpectra.*

and for the correlations:
R3BFiberMAPMTCorrelationOnlineSpectra

I still need to implement your last modifications (S522) in the class R3BFiberMAPMTOnlineSpectra

**Comment by jose-luis-rs** [comment]
Ready!
