### ISSUE TITLE
Unpack Califa Data to Hit level

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#567]
Hello!

I know this is a simple question but I'm always quite confused on how to do this.

I have 26gb of muon data that we collected of CALIFA in proton range that I want to unpack. I'm using a script called unpack_califa.C (attached) and it only gives me the data at the Cal level, I give it a Calibration file and a parameter file (/u/land/fake_cvmfs/9.13/upexps/202202_para/202202_para).
[califa_unpack (copy).txt](https://github.com/R3BRootGroup/R3BRoot/files/8660125/califa_unpack.copy.txt)

I'm sourcing R3BRoot in /u/land/tsousa/R3BRoot_build/config.sh.

I want in the end to have a calibrated histogram for every crystal. Do I want data at Hit level? If so, how? Because when I try and use this unpack_califa.C file I get an error for the SetDetectorThreshold() class being no existent.

**Comment by jose-luis-rs** [comment]
In the current online macro for CALIFA you can see how to call the calibration tasks:
https://github.com/R3BRootGroup/R3BParams_S522/blob/dev/macros/exp/online/califa/califa_online.C
I hope this works

PS: I should have access to the R3BParams_S522 repository according to our database

**Comment by tcsousa99** [comment]
Thank you, I had no idea that this repo existed!

But I want to have a .root file at the end, I know I should change the --stream to the .lmd files but do I need to change anything else if I want the file and not online analysis?

**Comment by jose-luis-rs** [comment]
Initially you only need to change these flags:
Bool_t NOTstoremappeddata = true; // if true, don't store mapped data in the root file
Bool_t NOTstorecaldata = true;    // if true, don't store cal data in the root file
Bool_t NOTstorehitdata = true;    // if true, don't store hit data in the root file
and then the data will be stored in the root file.
