### ISSUE TITLE
FOOT StripCal2Hit overrun?

### ISSUE THREAD

**Issue by hanstt** [R3BRootGroup/R3BRoot#606]
The FOOT parameter loading and calibration for StripCal2Hit has what looks like a buffer overrun, but we haven't pinpointed the problem. This supposedly worked with whatever commits were used during the s522 test beam run. A fresh version of R3BRoot/dev, macros/dev, and R3BParams_s522 from /u/land/ (running R3BParams_S522/macros/exp/online/foot/online_foot.C on recorded lmd files) gives the following:

- Vanilla:
  - fFootCalData in R3BFootStripCal2Hit changes address (in Init = 0x55650ddb73c0 -> in Exec = 0x55651085e7d0),
  - GetEntries() == -2,
  - GetEntriesFast() == 1.
- With footMappingPar in footpar_v3.par commented:
  - fFootCalData keeps address (Init = Exec = 0x55f0266bf1e0),
  - GetEntries() == GetEntriesFast() == 0,1.
  - Looks fine, except no pars...
- Return in R3BFootMappingPar::getParams before getting pars:
  - Like previous.
- Return after footGeoPar:
  - Like previous.
- Return after footDetPar:
  - fFootCalData changes address (0x56369fea07d0 -> 0x5636a2948860),
  - GetEntries() == -2,
  - GetEntriesFast() == 1.

Looks like the last getter overwrites something bad, even though it's only 32-bit? One could continue trying to fill a var on the stack to see if it's the current object or the "filler" that causes problems.

**Comment by jose-luis-rs** [comment]
Thanks Hans, I will check it later.

**Comment by jose-luis-rs** [comment]
I think that the problem should be solved with my PR #609 
Please, @morze00 et al, check it.

**Comment by morze00** [comment]
Thank Jose Luis. We will check it

**Comment by jose-luis-rs** [comment]
This was fully solved with my last PR #638 
if not, reopen it
