### ISSUE TITLE
R3BRoot Installation

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#629]
Hello!

Would it be possible to have an updated page on how to install R3BRoot. In page in the wiki uses spack with a version of aug21 that does not even exist and when I tried using the "more stable one" in jun19 just gives a bunch of errors. I suppose it is just a matter of env variables.

**Comment by hapol** [comment]
Hi!
Sure, it would be possible... and even I have a perfect candidate for updating the wiki while installing the new versions... Please, feel free to update the page. Note that we (some developers) have updated it (and we plan to continue updating) when we (re-)install, but changes/updates are quite frequent. We do not have a core team checking the code and documenting continuously, it should be done by all of us as a community. So, please, feel free to ask for help if the R3BRoot installation fails, but the ultimate documentation and support for installing FAIRSOFT and FAIRRoot should be in the FAIRSOFT and FAIRRoot wiki documentation and teams, not us. Still, the section in our "Installing FairSoft and FairRoot" section should be modified if it is not accurate.
