### ISSUE TITLE
Could ExpId be contained in R3BEventHeader, instead of independent variables for each analysis task?

### ISSUE THREAD

**Issue by ryotani** [R3BRootGroup/R3BRoot#643]
Is it possible to store the experiment number (ExpId) in some containers globally accessible?

In some recent updates, there are new analysis methods added exclusively for specific experiments. To select the methods to be used, a variable ExpId is often added to their classes. Although the variable can be accessed with a mutator, `SetExpId(Int_t ExpId)`, I am afraid it can be forgotten by some users to specify the number upon such updates in the code. As a consequence, the code behaves not as expected for them unless they are keeping their eyes on every update. (For instance, see #632. While the original MwpcCal2Hit classes didn't have ExpId, the new updates require this to be specified and the initial value is set for the new method exclusively for the s455 experiment.)

Thus, I propose we define ExpId only once in a similar way as the RunId in R3BEventHeader (FairRootEventHeader), then each analysis task will refer to the EventHeader by an accessor in R3BEventHeader.
Thank you for considering it. If I don't hear any objections, I probably can make an update regarding this. (But of course, I will keep the mutator for each task remaining for those who would like to define ExpId independently.)

**Comment by jose-luis-rs** [comment]
Yes, please, do the implementation in the R3BEventHeader because that is the easier way.
Thanks in advance

**Comment by ryotani** [comment]
R3BRoot part is done with the commit above, I hope. Besides, still, Sofia repository requires to be updated. Is there any other repository to be looked into?

**Comment by ryotani** [comment]
Now I have updated the Sofia repository as well with the pull request of https://github.com/R3BRootGroup/sofia/pull/270.

**Comment by ryotani** [comment]
The upgrades concerning ExpId have been merged.
