### ISSUE TITLE
Crystal IDs of R3BCalifaHit

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#675]
Hello! 

I'm doing some analysis of the recently measure muon data with CALIFA. I found for some of the analysis, it would be great to have at the Hit level the Crystal IDs of the crystals in a cluster. This would allow to then know the "format" of the hit. 

Could there be any type of simple implementation that would result in a getter like GetCrystalIDs in a std::vector<Int_t> or some structure like that?

Maybe there's a way that I don't know to access this information or a bigger reason for why it is not available, but it would help me a big deal!

Kind regards,

**Comment by gabrigarjim** [comment]
Hi Tomás.
I will upload today (or tomorrow) a new version of the califa hit finder. Among other things it contains a new data member, which  is the ID list of the crystals that belong to the cluster. Specifically it is a vector<Int_t> that can be retrieved as **hit->GetCrystalList()** .

**Comment by tcsousa99** [comment]
Thank you very much @gabrigarjim!!!
