### ISSUE TITLE
Proposal: Move test cases to R3BRoot git repository 

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#688]
I do not understand why we keep the macros in a separate repository in the first place, when the general opinion is that using macros is not a bad thing. (I have to concede that on the glorious day when people realize that you can compile C++ to directly executable binary formats, and the root interpreter as an intermediary between earthly source code and the Machine is not actually required, it will be convenient to retcon the existence of any macros in our codebase.)

However, I think that separating the test cases from them main repository is a source of suffering. [0]

In particular: 
* For the macros repository containing our test cases, no CI takes place. PRs just get merged (irrespectively of them breaking R3BRoot CI). 
* R3BRoot CI uses the dev branch of macros for the tests. 

There is no good way to fix this while keeping two repositories.
* Using git submodules -- where you explicitly specify a commit in the submodule you want to use is bad because this means pinning each R3BRoot commit to one macros commit. Nobody likes commits with the message "updated submodule". 
* Specifying which macros version CI should use in some file just is a hack. (And anyhow would require that version to be merged by the time CI triggers)
* Making the test macros compatible with multiple R3BRoot commits using #ifdef is horrible. 

Thus my proposal: any macro which is used for CI testing gets migrated to R3BRoot. For bonus points, they should naturally be transformed to valid C++ and compiled using cmake.

[0] (It should be noted that suffering from root.exe -- like when it decides to spew header files at you because it could not load a library -- is arguably required to reach enlightenment. The suffering caused by the two repository issue is not related to macros in itself and thus pointless.)

**Comment by jose-luis-rs** [comment]
@klenze please, could you take care of this task?

**Comment by YanzhaoW** [comment]
Tests of NeuLAND have been already in `R3BRoot/neuland/`. I hope other detectors could follow.
