### ISSUE TITLE
Please enable -Werror in CI builds

### ISSUE THREAD

**Issue by inkdot7** [R3BRootGroup/R3BRoot#716]
Looking around the CI system, this is found (scroll to the last warning):

https://cdash.gsi.de/viewBuildError.php?type=1&buildid=359806

which references current (merged) code that indeed looks suspicious.  Either it should be a single `&`, or the `<<` is not needed:

https://github.com/R3BRootGroup/R3BRoot/blob/4e2decfab13d80ee412c6dfeabfcc19c4efd4976/analysis/online/R3BOnlineSpillAnalysis.cxx#L365

having the CI find such issues should be much cheaper than debugging them by hand later.

**Comment by klenze** [comment]
I am working on it in #718. 

At the moment, clang-format-8 still complains in CI. 
As clang-format-8 is not installed on lxir136, I will try to fix the formatting locally with clang-format-9.

**Comment by jose-luis-rs** [comment]
I think that we can close this issue.

**Comment by inkdot7** [comment]
I'm not able to follow how the CI jobs are run or what flags they set.  I assume the merged commit above solves the issue.

**Comment by jose-luis-rs** [comment]
It is made from the CMakeLists file, [here](
https://github.com/R3BRootGroup/R3BRoot/blob/e5e975dd601dc07330b1a35bc0df36fe5d8ee269/CMakeLists.txt#L223)
