### ISSUE TITLE
CI: clang-format todo

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#724]
My proposals for clang-format:
* Move it to a different top level task which gets executed before compilation
* Update .clang-format so that the behavior on lxir136 is compatible with the behavior on the CI machine. 
* Apply clang-format to all files
   * using a git username "whitespace" or something so it is clear in git blame (without -w) 
   * This needs sanity checking of the output, there might be some sections where some user carefully hand-formatted the code and clang-format should be disabled.

**Comment by ryotani** [comment]
Hi, I am not sure this is the right place to add the discussion, but I realised the travis-clang-format-check.sh has been deleted in the recent updates. How can I check the clang format before making PR? Also if we can still have an autofix feature as travis-clang had, that would be great...

**Comment by klenze** [comment]
I moved most of the shell scripts to util/.
util/clang-format-check.sh should still support the autofix option.

Cheers,
   Philipp

**Comment by jose-luis-rs** [comment]
From R3BRoot you can run it as:
. util/clang-format-check.sh

For sofia:
. clangformat_all.sh

I have to generalize it for all the repos, but I am busy with other projects, sorry for that!

**Comment by ryotani** [comment]
@klenze @jose-luis-rs Thanks. It worked!
