### ISSUE TITLE
CI: jobs do not run in parallel

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#737]
It is clear from the PR processing that the different CI jobs do not run in parallel. 

From the yaml files, it is not clear to me why this is. 

@jose-luis-rs: is this limit on one job at a time intentional? If yes, why?

If we can not fix this then I would suggest adding at least a 
```
  needs: clang-format
  if: always()
```
to all the other jobs so that the quick clang-format job is executed before any others, but compilation is still tried even if it fails.

**Comment by jose-luis-rs** [comment]
I guess that depends on the number of runners defined in https://cdash.gsi.de/viewSite.php?siteid=1197
I don't know if we can run all of them in parallel, maybe @kresan could comment on this point.

**Comment by kresan** [comment]
CI is executed on a single runner - parallelisation is not possible.

I agree that build should not start if clang-format fails.

**Comment by klenze** [comment]
> CI is executed on a single runner - parallelisation is not possible.

Can't we find a few more CPUs somewhere? From my understanding, github provides at least 20 runners and 2000 minutes per month for free even for non-public repositories, with public repositories being free (but still probably subject to some limitations?). Or we could set up an account with GSI IT for that purpose. lxir136 has cpu power to spare. 

> I agree that build should not start if clang-format fails.

I think the best thing would be for both tests to be independent of each other with clang-format being run first (or in parallel). 

If clang-format fails for my commit, I still want to get the information if build and tests were successful or not.

**Comment by inkdot7** [comment]
CI builders have to be treated very ... gingerly.  One has to assume they are hacked, so should not be on any internal networks.  Using github runners sounds like a good idea.

**Comment by klenze** [comment]
Yes. The VMs used by the runner are not a security measure because an attacker could just put arbitrary code in .github/workflows/. 

Also, having the CI images publicly available would be helpful to have a shorter round trip time when debugging. At the moment, each push takes ten minutes until the clang-format gets executed. Working on that feels a bit like remote controlling a mars rover.
