### ISSUE TITLE
GTest: Create gtest modules from CMake FetchContent

### ISSUE THREAD

**Issue by YanzhaoW** [R3BRootGroup/R3BRoot#738]
GTest module is not included in the FairSoft. A probable reason could be GTest module can be directly downloaded in Cmake FetchContent, according to GTest [website](https://google.github.io/googletest/quickstart-cmake.html).

Therefore, I suggest we could use this FetchContent in our main CMakeLists.txt to download gtest.

```cmake
include(FetchContent)
FetchContent_Declare(
  googletest
  GIT_REPOSITORY https://github.com/google/googletest.git
  GIT_TAG        release-1.12.1
)
FetchContent_MakeAvailable(googletest)

enable_testing()
add_executable(mytest mytest.cxx)
target_link_libraries(
    mytest
    GTest::gtest_main
    )

include (GoogleTest)
gtest_discover_tests(mytest)

```

#728

**Comment by klenze** [comment]
Personally, I would prefer it if we first searched for gtest locally (findpackage or something?) and only compiled it from github if it was not found. This would especially helpful for CI if we manage to get it into the container. 

We should also try to get it included in fairsoft.
