### ISSUE TITLE
dynamic_cast speed when iterating over TClonesArray

### ISSUE THREAD

**Issue by klenze** [R3BRootGroup/R3BRoot#755]
Last Thursday in the analysis meeting, @YanzhaoW raised the issue of speed when using dynamic_cast to iterate over members of a TClonesArray in the event loop. 

I have done some measurements. 

I ran /u/land/latar/s509/califa_offline_s509_philipp_test.C, which is adapted from @latar. It reads 10M events from a source run lmd file and applies R3BCalifaMapped2CrystalCal. I think this is a rather typical task: there is some computation going on per hit, but nothing too terrible. The test was done on lxir133 using my experimental jan23 environment. 

In one case, I used ``dynamic_cast``, and then replaced it with ``static_cast``

Here are the results:
```
#  dynamic_cast
real    4m40.430s
real    4m41.430s
real    4m44.917s # outlier
real    4m40.085s
real    4m40.917s
real    4m40.290s
real    4m40.590s
real    4m40.463s
# static_cast
real    4m39.777s
real    4m36.121s
real    4m37.285s
real    4m37.206s
real    4m38.272s
```

As you can see, the speed advantage to static_cast is tiny, on the ~~order of 1/250~~ **edit: order of one percent.** IMHO, this is plainly not worth it. 

When we ever come to the point where measurements show that the cast operator is the bottleneck, then we can discuss using static_cast in specific places and thinking about what guarantees we can have about the types within a TCA. Until that point, I think using dynamic_cast is reasonable in a world where compute is cheap and dev time is expensive.

**Comment by klenze** [comment]
> Well, from the document, dynamic_cast does additional runtime check while static _cast only does compile time check. So theoretically static_cast should be much faster than dynamic_cast.

For shallow class hierarchies, a successful dynamic_cast + branch will take seven times as many CPU cycles as a static cast _iff you literally do nothing else with the pointer_. (Per [0])

This condition is obviously not very realistic. After all, few people loop over a collection of pointers and do not dereference them. 

If you do dereference them cache prefetching will possibly already load the VPTR of the class into your CPU cache. (Also, obviously, if you call any virtual method.)

My dynamic and static casts replaced the c-style cast in line here: [here](https://github.com/R3BRootGroup/R3BRoot/blob/dev/califa/calibration/R3BCalifaMapped2CrystalCal.cxx#L227). The fact that there is a measurable runtime difference is a clear indication that the compiler does not optimize it away. Also, this optimization would require information from at least two compile units at the same time (plus the assumption that no other compile units will add other TObjects to the TCA), so I would be amazed if any compiler could optimize this away. 

I am not totally surprised by my results. Personally, I might have guessed that the impact is a bit larger (say a few percents of the runtime), but would have been very surprised if the impact of the cast was large (e.g. 50% slower). 

I think like virtual methods, dynamic_casts are reasonably fast under most circumstances. If you are optimizing the runtime of a few lines of code, then getting rid of anything using VPTR (and statically making sure that all the assumptions still hold) will likely be helpful. This is not our typical use case. Our use case is that the runtime is spend in thousands of lines of various Exec methods and we do not even have the manpower (personpower?) to optimize algorithms (e.g. we search for keys by looping through TCAs in $O(n)$).

[0] https://blog.michael.franzl.name/2021/03/21/performance-comparison-of-three-different-implementations-of-dynamic_cast/

**Comment by klenze** [comment]
I think we should try a before and after test with a realistic experiment analysis (multiple detectors, all with multiple levels). 

I think that parts which are already non-optimal may suffer: if one searches through a TCA of length n for each element (total $O(n^2))$ and only checks a single field (which the compiler could optimize into pointer arithmetic), then using dynamic_cast could easily be five times more expensive. The real fix would be to populate a ``std::map<key_t, R3BFooData*>`` in $O(n)$ with dynamic cast and search in $O(log(n))$.

**Comment by YanzhaoW** [comment]
> if one searches through a TCA of length n for each element (total O(n^2) ) and only checks a single field (which the compiler could optimize into pointer arithmetic)

Is this a process in Califa data analysis? Matching process is very expensive, and even more with unsafe data type. Is it possible to do the casting first for the whole TCA and then match?

**Comment by jose-luis-rs** [comment]
Maybe you can also close this!
