### ISSUE TITLE
NeuLAND: Update R3BNeulandMCMon to avoid warnings

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#779]
R3BRoot/neuland/simulation/R3BNeulandMCMon.cxx: In instantiation of ‘void writeout(std::map<T, TH1D*>&, const string&, int) [with T = int; std::string = std::basic_string<char>]’:
R3BRoot/neuland/simulation/R3BNeulandMCMon.cxx:647:54:   required from here
R3BRoot/neuland/simulation/R3BNeulandMCMon.cxx:77:69: warning: ‘TFile* FairRun::GetOutputFile()’ is deprecated [-Wdeprecated-declarations]
             const std::string f = FairRun::Instance()->GetOutputFile()->GetName() + std::string(".") + what + ".dat";

New options from FairRoot:
  -  void SetUserOutputFileName(const TString& name);
  -  TString **GetUserOutputFileName**() const;

**Comment by YanzhaoW** [comment]
Ok, I will create a new PR to fix this issue.

**Comment by jose-luis-rs** [comment]
Thanks!
