### ISSUE TITLE
CI: Please upgrade FairRoot and stdc++ in C++17 CI

### ISSUE THREAD

**Issue by YanzhaoW** [R3BRootGroup/R3BRoot#782]
The analysis machines from GSI have been already using the FairRoot of version 18.8.0. Please upgrade the FairRoot in our C++17 CI.

Two month ago in PR #728, I already suggested that the version of default stdc++ library is too old for the gcc version we use for the compilation. Below is my exact request back then:
> listdc++ has version 3.4. Is it the correct version for gcc8.3? In this [list](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html), the version of libstdc++ is 6.0 for gcc 8.1. The executable works with libstdc++ 6.0.28 with gcc 10.

Without the correction version of stdc++, executables couldn't be run and CI test would fail.

**Comment by jose-luis-rs** [comment]
Yes, there is a PR for this #775 , but @kresan is still working on some details.

**Comment by YanzhaoW** [comment]
> Yes, there is a PR for this #775 , but @kresan is still working on some details.

@kresan Are you also fixing the stdc++ version? As far as I know, this needs to be done in the container?

**Comment by kresan** [comment]
@YanzhaoW, if you have requirements on stdc++ version in CI, you need to come up with the container definition where you install your non-system gcc and use it for building of FairSoft and FairRoot. You can build it on top of existing def files from the #775. I will then put it in the right place on lxbuild07.gsi.de.

Number of tests in R3BRoot CI has grown and GSI internal machine lxbuild07 is not meant and is not suitable for that. On the long run R3BRoot should use GitHub runners.

In addition to that, gaining experience in writing and creating singularity containers is of great advantage when you go for runs on GSI Virgo cluster.

**Comment by YanzhaoW** [comment]
> @YanzhaoW, if you have requirements on stdc++ version in CI, you need to come up with the container definition where you install your non-system gcc and use it for building of FairSoft and FairRoot. You can build it on top of existing def files from the #775. I will then put it in the right place on lxbuild07.gsi.de.
> 
> Number of tests in R3BRoot CI has grown and GSI internal machine lxbuild07 is not meant and is not suitable for that. On the long run R3BRoot should use GitHub runners.
> 
> In addition to that, gaining experience in writing and creating singularity containers is of great advantage when you go for runs on GSI Virgo cluster.

Thanks. I will try to do that. What is the version of singularity in lxbuild07?

**Comment by kresan** [comment]
`singularity version 3.8.0`

**Comment by jose-luis-rs** [comment]
Hello, 
I guess we also need a file like this **singularity exec /data.local2/kresan/debian10-apr22-v18.6.8-ucesb.sif**
right?

**Comment by YanzhaoW** [comment]
@jose-luis-rs  Yes, did you succeed to build the container from this .def file? I tried to build it both from my machine and from the remote server of sylab. Neither of them are successful during the compilation of FairSoft.

**Comment by YanzhaoW** [comment]
@kresan Could you explain to me what these lines do in .def file?

```shell
mkdir -p ~/.subversion
echo '[global]
http-proxy-host = proxy.gsi.de
http-proxy-port = 3128' > ~/.subversion/servers
```

**Comment by kresan** [comment]
Those are GSI-internal proxy settings for the subversion. Not necessary if one prepares container for the GitHub-hosted runner.

Side remark: subversion is needed during FairSoft build to check out some repositories.
