### ISSUE TITLE
Califa Geo - lxir136

### ISSUE THREAD

**Issue by lr11345** [R3BRootGroup/R3BRoot#801]
Hi,

i am analysing s467, with the upgrade of analysis pc lxir136 i was checking the new CALIFA geometries produced and used open gl on the lxir136.(see attached)

this is using the "2020" version.

Do others see this ? Is this a feature of open gl  through lxir136 or is this a fault in geometry ?

Kind regards

Luke
![CalifaGeo](https://user-images.githubusercontent.com/79202211/218486797-cf2c25af-da9a-4aab-ae27-56eb8f65c242.png)

**Comment by hapol** [comment]
Hi,
yes, it was reported that the geometry generated with nov22 has changed. It is not a visual thing, something related with the transformation of the objects is different in this version. Thank you for reporting this issue.
We should check as soon as we can install nov22 (we are using apr22 locally).

**Comment by jose-luis-rs** [comment]
I will do a PR to solve **temporarily** this problem. My basic solution will give time to @hapol to understand this issue.

**Comment by klenze** [comment]
@lr11345 added workaround in [R3Brc #1](https://github.com/R3BRCDevs/R3Brc/pull/1).

**Comment by jose-luis-rs** [comment]
This was solved with PR #915
