### ISSUE TITLE
Weird timestamps from unpacker 202103_s455

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#807]
**Describe the bug**
The timestamps provided by the unpacker 202103_s455 don't have the right units as can be seen in the attached figure.

**To Reproduce**
- ucesb: origin/master, commit 25b887a
- upexps; origin/master, commit e8dd606
- lmd files from run0273
Just check the timestamps provided by the unpacker.

**Expected behavior**
TImestamps should be in ns, after dividing by 10⁹ it should be in s. The spill length was 7 s, so I expect 7s of spill ON and 2-3s for spill OFF.

**Logs / Screenshots**
If applicable, add logs or screenshots to help explain your problem.
![Screenshot from 2023-02-14 15-14-47](https://user-images.githubusercontent.com/18137822/218765165-ea5829e5-0c91-4e9f-97ed-7ffc49e2389e.png)

**Comment by ryotani** [comment]
Hi, the definition of the off-spill (or acceleration) period should be 1s (even though we don't get the beam on target due to the poor extraction). Can you gate on the tpat to select on-spill only for the plot?

**Comment by jose-luis-rs** [comment]
I have been that for this specific experiment my standard analysis macro does not get properly the first timestamp, defining it by hand, I can recover the expected tendency.

![Screenshot from 2023-02-14 16-40-57](https://user-images.githubusercontent.com/18137822/218785918-92760955-08a0-450d-b547-01949e6339ef.png)

Sorry for disturbing with this.

**Comment by jose-luis-rs** [comment]
Well, the first timestamp is zero, but it should be > 0.
