### ISSUE TITLE
Unknown Type name 'FairMCTracks'

### ISSUE THREAD

**Issue by tcsousa99** [R3BRootGroup/R3BRoot#839]
**Describe the bug**
This is a recent bug I found when trying to view simulations with eventDisplay.C in a fresh R3BRoot installation.

**To Reproduce**
1. Just open the macros and run "root -l run_sim.C" and then "root -l eventDisplay.C"

**Expected behavior**
It would be expected to open a GUI to check the tracks.

**Logs / Screenshots**

Processing eventDisplay.C...
In file included from input_line_8:1:
/home/tomas/Programs/R3BRoot/R3BRoot/macros/r3b/eventDisplay.C:15:3: error: unknown type name 'FairMCTracks'
  FairMCTracks *Track =  new FairMCTracks ("Monte-Carlo Tracks");
  ^
/home/tomas/Programs/R3BRoot/R3BRoot/macros/r3b/eventDisplay.C:15:30: error: unknown type name 'FairMCTracks'
  FairMCTracks *Track =  new FairMCTracks ("Monte-Carlo Tracks");
                             ^
root.exe: /home/tomas/Programs/FairSoft/build/Source/root/interpreter/llvm/src/tools/clang/include/clang/AST/DeclContextInternals.h:120: void clang::StoredDeclsList::remove(clang::NamedDecl*): Assertion `llvm::find(Vec, D) == Vec.end() && "list still contains decl"' failed.

**System information (please complete the following information):**
 - OS: Ubuntu 22.04
 - Environment: FairSoft april 22 patches, FairRoot v18.8_patches, R3BRoot dev, macros dev

@jose-luis-rs @hapol

**Comment by jose-luis-rs** [comment]
I think that the repository macros is not updated, please, use this macro:
https://github.com/R3BRootGroup/R3BParams_workshop/blob/dev/macros/sim/event_display.C
from our last workshop.

Cheers
