### ISSUE TITLE
Bug CALIFA QPID Simulation 

### ISSUE THREAD

**Issue by lr11345** [R3BRootGroup/R3BRoot#853]
Hi,

I am simulating (p,2p) events in CALIFA and then looking at QPID.
It appears at the Point level to the Cluster level i see these sort of jumps and was wondering if this is to do with the step length.
Is there a way of modifying this for either a detector by detector basis or for materials so i can check if this is the origin?

Kind regards

Luke
![image](https://user-images.githubusercontent.com/79202211/234631568-923fa223-a987-485e-87be-951a41975142.png)

**Comment by jose-luis-rs** [comment]
Hello Luke
Please, indicate the commit of your R3BRoot version
Cheers

**Comment by lr11345** [comment]
Hi Jose Luis,

I checkout  the newest versions of everything in a new repo

Kind regards

Luke

**Comment by jose-luis-rs** [comment]
Hello
I think that first you must check the Ns-Nf algorithm implemented in R3BCalifa.cxx, 
I would say that nobody tested it in the last years. 
Cheers

**Comment by jose-luis-rs** [comment]
This is solved with PR #914
