### ISSUE TITLE
Problems with the compilation of new reader data structures: TTTX

### ISSUE THREAD

**Issue by jose-luis-rs** [R3BRootGroup/R3BRoot#917]
**Describe the bug**

R3BTTTXReader.cxx: In member function ‘virtual Bool_t R3BTTTXReader::Init(ext_data_struct_info*)’:
R3BRoot/r3bsource/ttt10/ext_h101_ttt10.h:117:56: error: expected primary-expression before ‘,’ token
  117 |         EXT_STR_ITEM_INFO2_LIM(ok, si, offset, struct_t, printerr, TTTX_ID1EM, UINT32, "TTTX_ID1EM", 32, 0 /*flags*/); \

**To Reproduce**
FairRoot 18.6.8
R3BRoot dev

Compilation on GSI PCs is ok, but on external PCs fails, 
why? 
is this related to ucesb version?

**Comment by ryotani** [comment]
What happens if you copy the ucesb in gsi computer? I have added a definition of mdpp32. But the commit has not been accepted yet to the main repository.

**Comment by jose-luis-rs** [comment]
Thanks Ryo!

**Comment by ryotani** [comment]
Could you let me know if it works? @jose-luis-rs 

This is the information for others who would encounter the same issues.
It is in the following directory. Two files need to be added apparently.
```
land@lxir136:spec > pwd
/u/land/fake_cvmfs/10/cvmfs_fairroot_v18.8.0_fs_nov22p1_extra/ucesb/spec
land@lxir136:spec > git diff --stat HEAD^
 spec/spec.spec               |   1 +
 spec/vme_mesytec_mdpp32.spec | 104 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 105 insertions(+)
```

**Comment by jose-luis-rs** [comment]
Yes, it is now OK.
